'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ClimsoftVer4.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About.
        '''</summary>
        Public ReadOnly Property About() As String
            Get
                Return ResourceManager.GetString("About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Accessories.
        '''</summary>
        Public ReadOnly Property Accessories() As String
            Get
                Return ResourceManager.GetString("Accessories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property addNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property addNew1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addNew1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property addNew2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addNew2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property addNew3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addNew3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Administration.
        '''</summary>
        Public ReadOnly Property Administration() As String
            Get
                Return ResourceManager.GetString("Administration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apply.
        '''</summary>
        Public ReadOnly Property Apply() As String
            Get
                Return ResourceManager.GetString("Apply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archive Paper Image.
        '''</summary>
        Public ReadOnly Property Archive_Paper_Image() As String
            Get
                Return ResourceManager.GetString("Archive_Paper_Image", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AWS Real Time Processing.
        '''</summary>
        Public ReadOnly Property AWS_Real_Time_Processing() As String
            Get
                Return ResourceManager.GetString("AWS_Real_Time_Processing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calculation of dew Point and RH.
        '''</summary>
        Public ReadOnly Property Calculation_of_dew_Point_and_RH() As String
            Get
                Return ResourceManager.GetString("Calculation_of_dew_Point_and_RH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Public ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Climate Data Management System.
        '''</summary>
        Public ReadOnly Property Climate_Data_Management_System() As String
            Get
                Return ResourceManager.GetString("Climate_Data_Management_System", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Climate Data Products.
        '''</summary>
        Public ReadOnly Property Climate_Data_Products() As String
            Get
                Return ResourceManager.GetString("Climate_Data_Products", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Public ReadOnly Property Close() As String
            Get
                Return ResourceManager.GetString("Close", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property COIN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COIN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contents.
        '''</summary>
        Public ReadOnly Property Contents() As String
            Get
                Return ResourceManager.GetString("Contents", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Entry.
        '''</summary>
        Public ReadOnly Property Data_Entry() As String
            Get
                Return ResourceManager.GetString("Data_Entry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Forms.
        '''</summary>
        Public ReadOnly Property Data_Forms() As String
            Get
                Return ResourceManager.GetString("Data_Forms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Transfer Operations.
        '''</summary>
        Public ReadOnly Property Data_Transfer_Operations() As String
            Get
                Return ResourceManager.GetString("Data_Transfer_Operations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generate XML Output.
        '''</summary>
        Public ReadOnly Property Generate_XML_Output() As String
            Get
                Return ResourceManager.GetString("Generate_XML_Output", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Public ReadOnly Property Help() As String
            Get
                Return ResourceManager.GetString("Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hide Database Details.
        '''</summary>
        Public ReadOnly Property Hide_Database_Details() As String
            Get
                Return ResourceManager.GetString("Hide_Database_Details", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Input.
        '''</summary>
        Public ReadOnly Property Input() As String
            Get
                Return ResourceManager.GetString("Input", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Key Entry.
        '''</summary>
        Public ReadOnly Property Key_Entry() As String
            Get
                Return ResourceManager.GetString("Key_Entry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login.
        '''</summary>
        Public ReadOnly Property Login() As String
            Get
                Return ResourceManager.GetString("Login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Main Menu.
        '''</summary>
        Public ReadOnly Property Main_Menu() As String
            Get
                Return ResourceManager.GetString("Main_Menu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Metadata.
        '''</summary>
        Public ReadOnly Property Metadata() As String
            Get
                Return ResourceManager.GetString("Metadata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Metadata Information.
        '''</summary>
        Public ReadOnly Property Metadata_Information() As String
            Get
                Return ResourceManager.GetString("Metadata_Information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modify Forms.
        '''</summary>
        Public ReadOnly Property Modify_Forms() As String
            Get
                Return ResourceManager.GetString("Modify_Forms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property MySql_Data() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MySql_Data", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Public ReadOnly Property OK() As String
            Get
                Return ResourceManager.GetString("OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Options.
        '''</summary>
        Public ReadOnly Property Options() As String
            Get
                Return ResourceManager.GetString("Options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paper Archive.
        '''</summary>
        Public ReadOnly Property Paper_Archive() As String
            Get
                Return ResourceManager.GetString("Paper_Archive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Public ReadOnly Property Password() As String
            Get
                Return ResourceManager.GetString("Password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Wait.
        '''</summary>
        Public ReadOnly Property Please_Wait() As String
            Get
                Return ResourceManager.GetString("Please_Wait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Products.
        '''</summary>
        Public ReadOnly Property Products() As String
            Get
                Return ResourceManager.GetString("Products", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quality Control Checks.
        '''</summary>
        Public ReadOnly Property Quality_Control_Checks() As String
            Get
                Return ResourceManager.GetString("Quality_Control_Checks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Language.
        '''</summary>
        Public ReadOnly Property Select_Language() As String
            Get
                Return ResourceManager.GetString("Select_Language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show Database Details.
        '''</summary>
        Public ReadOnly Property Show_Database_Details() As String
            Get
                Return ResourceManager.GetString("Show_Database_Details", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tools.
        '''</summary>
        Public ReadOnly Property Tools() As String
            Get
                Return ResourceManager.GetString("Tools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Element Limits.
        '''</summary>
        Public ReadOnly Property Update_Element_Limits() As String
            Get
                Return ResourceManager.GetString("Update_Element_Limits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User Admin.
        '''</summary>
        Public ReadOnly Property User_Admin() As String
            Get
                Return ResourceManager.GetString("User_Admin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Username.
        '''</summary>
        Public ReadOnly Property Username() As String
            Get
                Return ResourceManager.GetString("Username", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Users Administration.
        '''</summary>
        Public ReadOnly Property Users_Administration() As String
            Get
                Return ResourceManager.GetString("Users_Administration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version.
        '''</summary>
        Public ReadOnly Property Version() As String
            Get
                Return ResourceManager.GetString("Version", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
