'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.18408
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ClimsoftVer4.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à About.
        '''</summary>
        Public ReadOnly Property About() As String
            Get
                Return ResourceManager.GetString("About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Accessories.
        '''</summary>
        Public ReadOnly Property Accessories() As String
            Get
                Return ResourceManager.GetString("Accessories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property addNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property addNew1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addNew1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property addNew2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addNew2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property addNew3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addNew3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Administration.
        '''</summary>
        Public ReadOnly Property Administration() As String
            Get
                Return ResourceManager.GetString("Administration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Apply.
        '''</summary>
        Public ReadOnly Property Apply() As String
            Get
                Return ResourceManager.GetString("Apply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Archive Paper Image.
        '''</summary>
        Public ReadOnly Property Archive_Paper_Image() As String
            Get
                Return ResourceManager.GetString("Archive_Paper_Image", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attach Uncoded Data.
        '''</summary>
        Public ReadOnly Property Attach_Uncoded_Data() As String
            Get
                Return ResourceManager.GetString("Attach_Uncoded_Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à AWS Real Time Processing.
        '''</summary>
        Public ReadOnly Property AWS_Real_Time_Processing() As String
            Get
                Return ResourceManager.GetString("AWS_Real_Time_Processing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à BBB.
        '''</summary>
        Public ReadOnly Property BBB() As String
            Get
                Return ResourceManager.GetString("BBB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Binary Message.
        '''</summary>
        Public ReadOnly Property Binary_Message() As String
            Get
                Return ResourceManager.GetString("Binary_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à BUFR edition Number.
        '''</summary>
        Public ReadOnly Property BUFR_edition_Number() As String
            Get
                Return ResourceManager.GetString("BUFR_edition_Number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à BUFR Master Table Version Number.
        '''</summary>
        Public ReadOnly Property BUFR_Master_Table_Version_Number() As String
            Get
                Return ResourceManager.GetString("BUFR_Master_Table_Version_Number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Calculation of dew Point and RH.
        '''</summary>
        Public ReadOnly Property Calculation_of_dew_Point_and_RH() As String
            Get
                Return ResourceManager.GetString("Calculation_of_dew_Point_and_RH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cancel.
        '''</summary>
        Public ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Character Message.
        '''</summary>
        Public ReadOnly Property Character_Message() As String
            Get
                Return ResourceManager.GetString("Character_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Climate Data Management System.
        '''</summary>
        Public ReadOnly Property Climate_Data_Management_System() As String
            Get
                Return ResourceManager.GetString("Climate_Data_Management_System", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Climate Data Products.
        '''</summary>
        Public ReadOnly Property Climate_Data_Products() As String
            Get
                Return ResourceManager.GetString("Climate_Data_Products", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Close.
        '''</summary>
        Public ReadOnly Property Close() As String
            Get
                Return ResourceManager.GetString("Close", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Close.
        '''</summary>
        Public ReadOnly Property Close1() As String
            Get
                Return ResourceManager.GetString("Close1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Coded Output.
        '''</summary>
        Public ReadOnly Property Coded_Output() As String
            Get
                Return ResourceManager.GetString("Coded_Output", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property COIN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COIN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Contents.
        '''</summary>
        Public ReadOnly Property Contents() As String
            Get
                Return ResourceManager.GetString("Contents", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Crex Editions Number.
        '''</summary>
        Public ReadOnly Property Crex_Editions_Number() As String
            Get
                Return ResourceManager.GetString("Crex_Editions_Number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Crex Table Version Number .
        '''</summary>
        Public ReadOnly Property Crex_Table_Version_Number() As String
            Get
                Return ResourceManager.GetString("Crex_Table_Version_Number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Data Category.
        '''</summary>
        Public ReadOnly Property Data_Category() As String
            Get
                Return ResourceManager.GetString("Data_Category", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Data Category Sub Category.
        '''</summary>
        Public ReadOnly Property Data_Category_Sub_Category() As String
            Get
                Return ResourceManager.GetString("Data_Category_Sub_Category", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Data Entry.
        '''</summary>
        Public ReadOnly Property Data_Entry() As String
            Get
                Return ResourceManager.GetString("Data_Entry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Data Forms.
        '''</summary>
        Public ReadOnly Property Data_Forms() As String
            Get
                Return ResourceManager.GetString("Data_Forms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Data Transfer Operations.
        '''</summary>
        Public ReadOnly Property Data_Transfer_Operations() As String
            Get
                Return ResourceManager.GetString("Data_Transfer_Operations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Day.
        '''</summary>
        Public ReadOnly Property Day() As String
            Get
                Return ResourceManager.GetString("Day", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Email.
        '''</summary>
        Public ReadOnly Property Email() As String
            Get
                Return ResourceManager.GetString("Email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Encode.
        '''</summary>
        Public ReadOnly Property Encode() As String
            Get
                Return ResourceManager.GetString("Encode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Evaporation.
        '''</summary>
        Public ReadOnly Property Evaporation() As String
            Get
                Return ResourceManager.GetString("Evaporation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à FTP.
        '''</summary>
        Public ReadOnly Property FTP() As String
            Get
                Return ResourceManager.GetString("FTP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Generate XML Output.
        '''</summary>
        Public ReadOnly Property Generate_XML_Output() As String
            Get
                Return ResourceManager.GetString("Generate_XML_Output", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Header.
        '''</summary>
        Public ReadOnly Property Header() As String
            Get
                Return ResourceManager.GetString("Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Help.
        '''</summary>
        Public ReadOnly Property Help() As String
            Get
                Return ResourceManager.GetString("Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Help.
        '''</summary>
        Public ReadOnly Property Help1() As String
            Get
                Return ResourceManager.GetString("Help1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Hide Database Details.
        '''</summary>
        Public ReadOnly Property Hide_Database_Details() As String
            Get
                Return ResourceManager.GetString("Hide_Database_Details", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Hour .
        '''</summary>
        Public ReadOnly Property Hour() As String
            Get
                Return ResourceManager.GetString("Hour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Include Check Digit.
        '''</summary>
        Public ReadOnly Property Include_Check_Digit() As String
            Get
                Return ResourceManager.GetString("Include_Check_Digit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Indicators.
        '''</summary>
        Public ReadOnly Property Indicators() As String
            Get
                Return ResourceManager.GetString("Indicators", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Input.
        '''</summary>
        Public ReadOnly Property Input() As String
            Get
                Return ResourceManager.GetString("Input", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Instrument Types.
        '''</summary>
        Public ReadOnly Property Instrument_Types() As String
            Get
                Return ResourceManager.GetString("Instrument_Types", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à International Data Sub-Category.
        '''</summary>
        Public ReadOnly Property International_Data_Sub_Category() As String
            Get
                Return ResourceManager.GetString("International_Data_Sub_Category", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Key Entry.
        '''</summary>
        Public ReadOnly Property Key_Entry() As String
            Get
                Return ResourceManager.GetString("Key_Entry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Local Data Sub-Category.
        '''</summary>
        Public ReadOnly Property Local_Data_Sub_Cateory() As String
            Get
                Return ResourceManager.GetString("Local_Data_Sub_Cateory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Login.
        '''</summary>
        Public ReadOnly Property Login() As String
            Get
                Return ResourceManager.GetString("Login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mail Applications.
        '''</summary>
        Public ReadOnly Property Mail_Applications() As String
            Get
                Return ResourceManager.GetString("Mail_Applications", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Main Menu.
        '''</summary>
        Public ReadOnly Property Main_Menu() As String
            Get
                Return ResourceManager.GetString("Main_Menu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Masters Table Version Number.
        '''</summary>
        Public ReadOnly Property Masters_Table_Version_Number() As String
            Get
                Return ResourceManager.GetString("Masters_Table_Version_Number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Metadata.
        '''</summary>
        Public ReadOnly Property Metadata() As String
            Get
                Return ResourceManager.GetString("Metadata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Metadata Information.
        '''</summary>
        Public ReadOnly Property Metadata_Information() As String
            Get
                Return ResourceManager.GetString("Metadata_Information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Minute.
        '''</summary>
        Public ReadOnly Property Minute() As String
            Get
                Return ResourceManager.GetString("Minute", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Modify Forms.
        '''</summary>
        Public ReadOnly Property Modify_Forms() As String
            Get
                Return ResourceManager.GetString("Modify_Forms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Month.
        '''</summary>
        Public ReadOnly Property Month() As String
            Get
                Return ResourceManager.GetString("Month", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Byte[].
        '''</summary>
        Public ReadOnly Property MySql_Data() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MySql_Data", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property navigation_first() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigation-first", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property navigation_last() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigation-last", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property navigation_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigation-left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property navigation_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("navigation-right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Number of Subsets.
        '''</summary>
        Public ReadOnly Property Number_Of_Subsets() As String
            Get
                Return ResourceManager.GetString("Number_Of_Subsets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à OK.
        '''</summary>
        Public ReadOnly Property OK() As String
            Get
                Return ResourceManager.GetString("OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Optional Sequence Inclusion.
        '''</summary>
        Public ReadOnly Property Optional_Sequence_Inclusion() As String
            Get
                Return ResourceManager.GetString("Optional_Sequence_Inclusion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Options.
        '''</summary>
        Public ReadOnly Property Options() As String
            Get
                Return ResourceManager.GetString("Options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Originating/Generating Center.
        '''</summary>
        Public ReadOnly Property Originating_Generating_Center() As String
            Get
                Return ResourceManager.GetString("Originating_Generating_Center", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Originating/Generating Centre.
        '''</summary>
        Public ReadOnly Property Originating_Generating_Centre() As String
            Get
                Return ResourceManager.GetString("Originating_Generating_Centre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Originating/Generating Sub Center.
        '''</summary>
        Public ReadOnly Property Originating_Generating_sub_Center() As String
            Get
                Return ResourceManager.GetString("Originating_Generating_sub_Center", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Originating/Generating Sub-Centre.
        '''</summary>
        Public ReadOnly Property Originating_Generating_SubCentre() As String
            Get
                Return ResourceManager.GetString("Originating_Generating_SubCentre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Paper Archive.
        '''</summary>
        Public ReadOnly Property Paper_Archive() As String
            Get
                Return ResourceManager.GetString("Paper_Archive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Password.
        '''</summary>
        Public ReadOnly Property Password() As String
            Get
                Return ResourceManager.GetString("Password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Please Wait.
        '''</summary>
        Public ReadOnly Property Please_Wait() As String
            Get
                Return ResourceManager.GetString("Please_Wait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Precipitation.
        '''</summary>
        Public ReadOnly Property Precipitation() As String
            Get
                Return ResourceManager.GetString("Precipitation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Pressure .
        '''</summary>
        Public ReadOnly Property Pressure() As String
            Get
                Return ResourceManager.GetString("Pressure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Products.
        '''</summary>
        Public ReadOnly Property Products() As String
            Get
                Return ResourceManager.GetString("Products", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Quality Control Checks.
        '''</summary>
        Public ReadOnly Property Quality_Control_Checks() As String
            Get
                Return ResourceManager.GetString("Quality_Control_Checks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Reset.
        '''</summary>
        Public ReadOnly Property Reset() As String
            Get
                Return ResourceManager.GetString("Reset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Select Language.
        '''</summary>
        Public ReadOnly Property Select_Language() As String
            Get
                Return ResourceManager.GetString("Select_Language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Send.
        '''</summary>
        Public ReadOnly Property Send() As String
            Get
                Return ResourceManager.GetString("Send", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sending Options.
        '''</summary>
        Public ReadOnly Property Sending_Options() As String
            Get
                Return ResourceManager.GetString("Sending_Options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sensors Height From Ground (M).
        '''</summary>
        Public ReadOnly Property Sensors_Height_From_Ground_M() As String
            Get
                Return ResourceManager.GetString("Sensors_Height_From_Ground_M", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sequence Number .
        '''</summary>
        Public ReadOnly Property Sequence_Number() As String
            Get
                Return ResourceManager.GetString("Sequence_Number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Settings .
        '''</summary>
        Public ReadOnly Property Settings() As String
            Get
                Return ResourceManager.GetString("Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Show Database Details.
        '''</summary>
        Public ReadOnly Property Show_Database_Details() As String
            Get
                Return ResourceManager.GetString("Show_Database_Details", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Station.
        '''</summary>
        Public ReadOnly Property Station() As String
            Get
                Return ResourceManager.GetString("Station", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Subject .
        '''</summary>
        Public ReadOnly Property Subject() As String
            Get
                Return ResourceManager.GetString("Subject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Local Tables Version Number.
        '''</summary>
        Public ReadOnly Property Table_Version_Number() As String
            Get
                Return ResourceManager.GetString("Table_Version_Number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Temperature .
        '''</summary>
        Public ReadOnly Property Temperature() As String
            Get
                Return ResourceManager.GetString("Temperature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Template.
        '''</summary>
        Public ReadOnly Property Template() As String
            Get
                Return ResourceManager.GetString("Template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Tools.
        '''</summary>
        Public ReadOnly Property Tools() As String
            Get
                Return ResourceManager.GetString("Tools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update Element Limits.
        '''</summary>
        Public ReadOnly Property Update_Element_Limits() As String
            Get
                Return ResourceManager.GetString("Update_Element_Limits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update Sequence Number.
        '''</summary>
        Public ReadOnly Property Update_Sequence_Number() As String
            Get
                Return ResourceManager.GetString("Update_Sequence_Number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à User Admin.
        '''</summary>
        Public ReadOnly Property User_Admin() As String
            Get
                Return ResourceManager.GetString("User_Admin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Username.
        '''</summary>
        Public ReadOnly Property Username() As String
            Get
                Return ResourceManager.GetString("Username", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Users Administration.
        '''</summary>
        Public ReadOnly Property Users_Administration() As String
            Get
                Return ResourceManager.GetString("Users_Administration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Version.
        '''</summary>
        Public ReadOnly Property Version() As String
            Get
                Return ResourceManager.GetString("Version", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à View/Import/Export.
        '''</summary>
        Public ReadOnly Property View_Import_Export() As String
            Get
                Return ResourceManager.GetString("View_Import_Export", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Visibility.
        '''</summary>
        Public ReadOnly Property Visibility() As String
            Get
                Return ResourceManager.GetString("Visibility", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Wind.
        '''</summary>
        Public ReadOnly Property Wind() As String
            Get
                Return ResourceManager.GetString("Wind", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Year.
        '''</summary>
        Public ReadOnly Property Year() As String
            Get
                Return ResourceManager.GetString("Year", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
