'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class aws_structures
    Public Property strID As Integer
    Public Property strName As String
    Public Property data_delimiter As String
    Public Property hdrRows As Integer
    Public Property txtQualifier As String

End Class
