'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class aws_sites
    Public Property SiteID As String
    Public Property SiteName As String
    Public Property InputFile As String
    Public Property DataStructure As String
    Public Property MissingDataFlag As String
    Public Property awsServerIP As String
    Public Property OperationalStatus As Boolean

End Class
