'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class aws_process_parameters
    Public Property RetrieveInterval As Integer
    Public Property HourOffset As Integer
    Public Property RetrievePeriod As Integer
    Public Property RetrieveTimeout As Integer
    Public Property DelinputFile As SByte

End Class
