'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class bufr_indicators
    Public Property Tmplate As String
    Public Property Msg_Header As String
    Public Property BUFR_Edition As String
    Public Property Originating_Centre As String
    Public Property Originating_SubCentre As String
    Public Property Update_Sequence As String
    Public Property Optional_Section As String
    Public Property Data_Category As String
    Public Property Intenational_Data_SubCategory As String
    Public Property Local_Data_SubCategory As String
    Public Property Master_table As String
    Public Property Local_Table As String

End Class
