'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class bufr_crex_master
    Public Property Bufr_FXY As String
    Public Property Crex_Fxxyyy As String
    Public Property ElementName As String
    Public Property Bufr_Unit As String
    Public Property Bufr_Scale As String
    Public Property Bufr_RefValue As String
    Public Property Bufr_DataWidth_Bits As String
    Public Property Crex_Unit As String
    Public Property Crex_Scale As String
    Public Property Crex_DataWidth As String
    Public Property Observation As String
    Public Property Crex_Data As String
    Public Property Bufr_Data As String

End Class
