'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class bufr_crex_data
    Public Property nos As Integer
    Public Property Bufr_Template As String
    Public Property Crex_Template As String
    Public Property Sequence_Descriptor1 As String
    Public Property Sequence_Descriptor0 As String
    Public Property Bufr_Element As String
    Public Property Crex_Element As String
    Public Property Climsoft_Element As String
    Public Property Element_Name As String
    Public Property Crex_Unit As String
    Public Property Crex_Scale As String
    Public Property Crex_DataWidth As String
    Public Property Bufr_Unit As String
    Public Property Bufr_Scale As String
    Public Property Bufr_RefValue As String
    Public Property Bufr_DataWidth_Bits As String
    Public Property selected As Nullable(Of SByte)
    Public Property Observation As String
    Public Property Crex_Data As String
    Public Property Bufr_Data As String

End Class
