'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ccitt
    Public Property id As Long
    Public Property Characters As String
    Public Property MostSignificant As Nullable(Of Integer)
    Public Property LeastSignificant As Nullable(Of Integer)

End Class
