'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class code_flag
    Public Property FXY As String
    Public Property Fxyyy As String
    Public Property Description As String
    Public Property Bufr_DataWidth_Bits As Nullable(Of Integer)
    Public Property Crex_DataWidth As String
    Public Property Bufr_Unit As String
    Public Property Bufr_Value As String
    Public Property Crex_Value As String

End Class
