'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class faultresolution
    Public Property id As Long
    Public Property resolvedDatetime As String
    Public Property resolvedBy As String
    Public Property associatedWith As Nullable(Of Long)
    Public Property remarks As String

    Public Overridable Property instrumentfaultreport As instrumentfaultreport

End Class
