'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class featuregeographicalposition
    Public Property belongsTo As String
    Public Property observedOn As Nullable(Of Date)
    Public Property latitude As Nullable(Of Double)
    Public Property longitude As Nullable(Of Double)

End Class
