'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class flagtable
    Public Property Bufr_Descriptor As String
    Public Property Crex_Descriptor As String
    Public Property Details As String
    Public Property Widths As Nullable(Of Integer)
    Public Property Missing As Nullable(Of Integer)

End Class
