'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class form_daily2
    Public Property id As Long
    Public Property stationId As String
    Public Property elementId As Integer
    Public Property yyyy As Integer
    Public Property mm As Integer
    Public Property hh As Integer
    Public Property day01 As String
    Public Property day02 As String
    Public Property day03 As String
    Public Property day04 As String
    Public Property day05 As String
    Public Property day06 As String
    Public Property day07 As String
    Public Property day08 As String
    Public Property day09 As String
    Public Property day10 As String
    Public Property day11 As String
    Public Property day12 As String
    Public Property day13 As String
    Public Property day14 As String
    Public Property day15 As String
    Public Property day16 As String
    Public Property day17 As String
    Public Property day18 As String
    Public Property day19 As String
    Public Property day20 As String
    Public Property day21 As String
    Public Property day22 As String
    Public Property day23 As String
    Public Property day24 As String
    Public Property day25 As String
    Public Property day26 As String
    Public Property day27 As String
    Public Property day28 As String
    Public Property day29 As String
    Public Property day30 As String
    Public Property day31 As String
    Public Property flag01 As String
    Public Property flag02 As String
    Public Property flag03 As String
    Public Property flag04 As String
    Public Property flag05 As String
    Public Property flag06 As String
    Public Property flag07 As String
    Public Property flag08 As String
    Public Property flag09 As String
    Public Property flag10 As String
    Public Property flag11 As String
    Public Property flag12 As String
    Public Property flag13 As String
    Public Property flag14 As String
    Public Property flag15 As String
    Public Property flag16 As String
    Public Property flag17 As String
    Public Property flag18 As String
    Public Property flag19 As String
    Public Property flag20 As String
    Public Property flag21 As String
    Public Property flag22 As String
    Public Property flag23 As String
    Public Property flag24 As String
    Public Property flag25 As String
    Public Property flag26 As String
    Public Property flag27 As String
    Public Property flag28 As String
    Public Property flag29 As String
    Public Property flag30 As String
    Public Property flag31 As String
    Public Property period01 As String
    Public Property period02 As String
    Public Property period03 As String
    Public Property period04 As String
    Public Property period05 As String
    Public Property period06 As String
    Public Property period07 As String
    Public Property period08 As String
    Public Property period09 As String
    Public Property period10 As String
    Public Property period11 As String
    Public Property period12 As String
    Public Property period13 As String
    Public Property period14 As String
    Public Property period15 As String
    Public Property period16 As String
    Public Property period17 As String
    Public Property period18 As String
    Public Property period19 As String
    Public Property period20 As String
    Public Property period21 As String
    Public Property period22 As String
    Public Property period23 As String
    Public Property period24 As String
    Public Property period25 As String
    Public Property period26 As String
    Public Property period27 As String
    Public Property period28 As String
    Public Property period29 As String
    Public Property period30 As String
    Public Property period31 As String
    Public Property total As String
    Public Property signature As String
    Public Property temperatureUnits As String
    Public Property precipUnits As String
    Public Property cloudHeightUnits As String
    Public Property visUnits As String

End Class
