'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class form_synoptic2_tdcf
    Public Property stationId As String
    Public Property yyyy As Long
    Public Property mm As Long
    Public Property dd As Long
    Public Property hh As String
    Public Property C106 As String
    Public Property C107 As String
    Public Property C399 As String
    Public Property C301 As String
    Public Property C185 As String
    Public Property C101 As String
    Public Property C103 As String
    Public Property C105 As String
    Public Property C110 As String
    Public Property C114 As String
    Public Property C115 As String
    Public Property C168 As String
    Public Property C192 As String
    Public Property C169 As String
    Public Property C170 As String
    Public Property C171 As String
    Public Property C119 As String
    Public Property C116 As String
    Public Property C117 As String
    Public Property C118 As String
    Public Property C123 As String
    Public Property C120 As String
    Public Property C121 As String
    Public Property C122 As String
    Public Property C127 As String
    Public Property C124 As String
    Public Property C125 As String
    Public Property C126 As String
    Public Property C131 As String
    Public Property C128 As String
    Public Property C129 As String
    Public Property C130 As String
    Public Property C167 As String
    Public Property C197 As String
    Public Property C193 As String
    Public Property C18 As String
    Public Property C532 As String
    Public Property C132 As String
    Public Property C5 As String
    Public Property C174 As String
    Public Property C3 As String
    Public Property C2 As String
    Public Property C112 As String
    Public Property C111 As String
    Public Property C85 As String
    Public Property flag1 As String
    Public Property flag2 As String
    Public Property flag3 As String
    Public Property flag4 As String
    Public Property flag5 As String
    Public Property flag6 As String
    Public Property flag7 As String
    Public Property flag8 As String
    Public Property flag9 As String
    Public Property flag10 As String
    Public Property flag11 As String
    Public Property flag12 As String
    Public Property flag13 As String
    Public Property flag14 As String
    Public Property flag15 As String
    Public Property flag16 As String
    Public Property flag17 As String
    Public Property flag18 As String
    Public Property flag19 As String
    Public Property flag20 As String
    Public Property flag21 As String
    Public Property flag22 As String
    Public Property flag23 As String
    Public Property flag24 As String
    Public Property flag25 As String
    Public Property flag26 As String
    Public Property flag27 As String
    Public Property flag28 As String
    Public Property flag29 As String
    Public Property flag30 As String
    Public Property flag31 As String
    Public Property flag32 As String
    Public Property flag33 As String
    Public Property flag34 As String
    Public Property flag35 As String
    Public Property flag36 As String
    Public Property flag37 As String
    Public Property flag38 As String
    Public Property flag39 As String
    Public Property flag40 As String
    Public Property flag41 As String
    Public Property flag42 As String
    Public Property flag43 As String
    Public Property flag44 As String
    Public Property flag45 As String
    Public Property signature As String

End Class
