'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class form_hourly
    Public Property stationId As String
    Public Property elementId As Integer
    Public Property yyyy As Integer
    Public Property mm As Integer
    Public Property dd As Integer
    Public Property hh_00 As String
    Public Property hh_01 As String
    Public Property hh_02 As String
    Public Property hh_03 As String
    Public Property hh_04 As String
    Public Property hh_05 As String
    Public Property hh_06 As String
    Public Property hh_07 As String
    Public Property hh_08 As String
    Public Property hh_09 As String
    Public Property hh_10 As String
    Public Property hh_11 As String
    Public Property hh_12 As String
    Public Property hh_13 As String
    Public Property hh_14 As String
    Public Property hh_15 As String
    Public Property hh_16 As String
    Public Property hh_17 As String
    Public Property hh_18 As String
    Public Property hh_19 As String
    Public Property hh_20 As String
    Public Property hh_21 As String
    Public Property hh_22 As String
    Public Property hh_23 As String
    Public Property flag00 As String
    Public Property flag01 As String
    Public Property flag02 As String
    Public Property flag03 As String
    Public Property flag04 As String
    Public Property flag05 As String
    Public Property flag06 As String
    Public Property flag07 As String
    Public Property flag08 As String
    Public Property flag09 As String
    Public Property flag10 As String
    Public Property flag11 As String
    Public Property flag12 As String
    Public Property flag13 As String
    Public Property flag14 As String
    Public Property flag15 As String
    Public Property flag16 As String
    Public Property flag17 As String
    Public Property flag18 As String
    Public Property flag19 As String
    Public Property flag20 As String
    Public Property flag21 As String
    Public Property flag22 As String
    Public Property flag23 As String
    Public Property total As String
    Public Property signature As String
    Public Property EntryDatetime As Nullable(Of Date)

End Class
