'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class form_agro1
    Public Property stationId As String
    Public Property yyyy As Integer
    Public Property mm As Integer
    Public Property dd As Integer
    Public Property Val_Elem101 As String
    Public Property Val_Elem102 As String
    Public Property Val_Elem103 As String
    Public Property Val_Elem105 As String
    Public Property Val_Elem002 As String
    Public Property Val_Elem003 As String
    Public Property Val_Elem099 As String
    Public Property Val_Elem072 As String
    Public Property Val_Elem073 As String
    Public Property Val_Elem074 As String
    Public Property Val_Elem554 As String
    Public Property Val_Elem075 As String
    Public Property Val_Elem076 As String
    Public Property Val_Elem561 As String
    Public Property Val_Elem562 As String
    Public Property Val_Elem563 As String
    Public Property Val_Elem513 As String
    Public Property Val_Elem005 As String
    Public Property Val_Elem504 As String
    Public Property Val_Elem532 As String
    Public Property Val_Elem137 As String
    Public Property Val_Elem018 As String
    Public Property Val_Elem518 As String
    Public Property Val_Elem511 As String
    Public Property Val_Elem512 As String
    Public Property Val_Elem503 As String
    Public Property Val_Elem515 As String
    Public Property Val_Elem564 As String
    Public Property Val_Elem565 As String
    Public Property Val_Elem566 As String
    Public Property Val_Elem531 As String
    Public Property Val_Elem530 As String
    Public Property Val_Elem541 As String
    Public Property Val_Elem542 As String
    Public Property Flag101 As String
    Public Property Flag102 As String
    Public Property Flag103 As String
    Public Property Flag105 As String
    Public Property Flag002 As String
    Public Property Flag003 As String
    Public Property Flag099 As String
    Public Property Flag072 As String
    Public Property Flag073 As String
    Public Property Flag074 As String
    Public Property Flag554 As String
    Public Property Flag075 As String
    Public Property Flag076 As String
    Public Property Flag561 As String
    Public Property Flag562 As String
    Public Property Flag563 As String
    Public Property Flag513 As String
    Public Property Flag005 As String
    Public Property Flag504 As String
    Public Property Flag532 As String
    Public Property Flag137 As String
    Public Property Flag018 As String
    Public Property Flag518 As String
    Public Property Flag511 As String
    Public Property Flag512 As String
    Public Property Flag503 As String
    Public Property Flag515 As String
    Public Property Flag564 As String
    Public Property Flag565 As String
    Public Property Flag566 As String
    Public Property Flag531 As String
    Public Property Flag530 As String
    Public Property Flag541 As String
    Public Property Flag542 As String
    Public Property signature As String
    Public Property entryDatetime As Nullable(Of Date)

End Class
