'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class form_monthly
    Public Property id As Long
    Public Property stationId As String
    Public Property elementId As Nullable(Of Integer)
    Public Property yyyy As Nullable(Of Integer)
    Public Property mm_01 As String
    Public Property mm_02 As String
    Public Property mm_03 As String
    Public Property mm_04 As String
    Public Property mm_05 As String
    Public Property mm_06 As String
    Public Property mm_07 As String
    Public Property mm_08 As String
    Public Property mm_09 As String
    Public Property mm_10 As String
    Public Property mm_11 As String
    Public Property mm_12 As String
    Public Property flag01 As String
    Public Property flag02 As String
    Public Property flag03 As String
    Public Property flag04 As String
    Public Property flag05 As String
    Public Property flag06 As String
    Public Property flag07 As String
    Public Property flag08 As String
    Public Property flag09 As String
    Public Property flag10 As String
    Public Property flag11 As String
    Public Property flag12 As String
    Public Property period01 As String
    Public Property period02 As String
    Public Property period03 As String
    Public Property period04 As String
    Public Property period05 As String
    Public Property period06 As String
    Public Property period07 As String
    Public Property period08 As String
    Public Property period09 As String
    Public Property period10 As String
    Public Property period11 As String
    Public Property period12 As String
    Public Property signature As String

End Class
