'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class form_synoptic_2_ra1
    Public Property id As Long
    Public Property stationId As String
    Public Property yyyy As Integer
    Public Property mm As Integer
    Public Property dd As Integer
    Public Property hh As Integer
    Public Property Val_Elem106 As String
    Public Property Val_Elem107 As String
    Public Property Val_Elem400 As String
    Public Property Val_Elem814 As String
    Public Property Val_Elem399 As String
    Public Property Val_Elem301 As String
    Public Property Val_Elem185 As String
    Public Property Val_Elem101 As String
    Public Property Val_Elem102 As String
    Public Property Val_Elem103 As String
    Public Property Val_Elem105 As String
    Public Property Val_Elem192 As String
    Public Property Val_Elem110 As String
    Public Property Val_Elem114 As String
    Public Property Val_Elem112 As String
    Public Property Val_Elem111 As String
    Public Property Val_Elem167 As String
    Public Property Val_Elem197 As String
    Public Property Val_Elem193 As String
    Public Property Val_Elem115 As String
    Public Property Val_Elem168 As String
    Public Property Val_Elem169 As String
    Public Property Val_Elem170 As String
    Public Property Val_Elem171 As String
    Public Property Val_Elem119 As String
    Public Property Val_Elem116 As String
    Public Property Val_Elem117 As String
    Public Property Val_Elem118 As String
    Public Property Val_Elem123 As String
    Public Property Val_Elem120 As String
    Public Property Val_Elem121 As String
    Public Property Val_Elem122 As String
    Public Property Val_Elem127 As String
    Public Property Val_Elem124 As String
    Public Property Val_Elem125 As String
    Public Property Val_Elem126 As String
    Public Property Val_Elem131 As String
    Public Property Val_Elem128 As String
    Public Property Val_Elem129 As String
    Public Property Val_Elem130 As String
    Public Property Val_Elem002 As String
    Public Property Val_Elem003 As String
    Public Property Val_Elem099 As String
    Public Property Val_Elem018 As String
    Public Property Val_Elem084 As String
    Public Property Val_Elem132 As String
    Public Property Val_Elem005 As String
    Public Property Val_Elem174 As String
    Public Property Val_Elem046 As String
    Public Property Flag106 As String
    Public Property Flag107 As String
    Public Property Flag400 As String
    Public Property Flag814 As String
    Public Property Flag399 As String
    Public Property Flag301 As String
    Public Property Flag185 As String
    Public Property Flag101 As String
    Public Property Flag102 As String
    Public Property Flag103 As String
    Public Property Flag105 As String
    Public Property Flag192 As String
    Public Property Flag110 As String
    Public Property Flag114 As String
    Public Property Flag112 As String
    Public Property Flag111 As String
    Public Property Flag167 As String
    Public Property Flag197 As String
    Public Property Flag193 As String
    Public Property Flag115 As String
    Public Property Flag168 As String
    Public Property Flag178 As String
    Public Property Flag179 As String
    Public Property Flag180 As String
    Public Property Flag119 As String
    Public Property Flag116 As String
    Public Property Flag117 As String
    Public Property Flag118 As String
    Public Property Flag123 As String
    Public Property Flag120 As String
    Public Property Flag121 As String
    Public Property Flag122 As String
    Public Property Flag127 As String
    Public Property Flag124 As String
    Public Property Flag125 As String
    Public Property Flag126 As String
    Public Property Flag131 As String
    Public Property Flag128 As String
    Public Property Flag129 As String
    Public Property Flag130 As String
    Public Property Flag002 As String
    Public Property Flag003 As String
    Public Property Flag099 As String
    Public Property Flag018 As String
    Public Property Flag084 As String
    Public Property Flag132 As String
    Public Property Flag005 As String
    Public Property Flag174 As String
    Public Property Flag046 As String
    Public Property signature As String
    Public Property entryDatetime As Nullable(Of Date)

End Class
