'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class instrumentinspection
    Public Property id As Long
    Public Property performedOn As String
    Public Property inspectionDatetime As String
    Public Property performedBy As String
    Public Property status As String
    Public Property remarks As String
    Public Property performedAt As String

    Public Overridable Property instrument As instrument
    Public Overridable Property station As station

End Class
