'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class instrumentfaultreport
    Public Property refersTo As String
    Public Property reportId As Long
    Public Property reportDatetime As Nullable(Of Date)
    Public Property faultDescription As String
    Public Property reportedBy As String
    Public Property receivedDatetime As Nullable(Of Date)
    Public Property receivedBy As String
    Public Property reportedFrom As String

    Public Overridable Property instrument As instrument
    Public Overridable Property station As station

End Class
