'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class missing_stats
    Public Property STN_ID As String
    Public Property ELEM As Long
    Public Property MISSING As Nullable(Of Long)
    Public Property Closing_Date As Date
    Public Property Opening_Date As Date

End Class
