'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class mariadb_climsoft_test_db_v4Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=mariadb_climsoft_test_db_v4Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property acquisitiontypes() As DbSet(Of acquisitiontype)
    Public Overridable Property aws_basestation() As DbSet(Of aws_basestation)
    Public Overridable Property aws_elements() As DbSet(Of aws_elements)
    Public Overridable Property aws_malawi1() As DbSet(Of aws_malawi1)
    Public Overridable Property aws_mss() As DbSet(Of aws_mss)
    Public Overridable Property aws_process_parameters() As DbSet(Of aws_process_parameters)
    Public Overridable Property aws_rwanda4() As DbSet(Of aws_rwanda4)
    Public Overridable Property aws_sasscal1() As DbSet(Of aws_sasscal1)
    Public Overridable Property aws_sites() As DbSet(Of aws_sites)
    Public Overridable Property aws_stations() As DbSet(Of aws_stations)
    Public Overridable Property aws_structures() As DbSet(Of aws_structures)
    Public Overridable Property aws_tahmo() As DbSet(Of aws_tahmo)
    Public Overridable Property aws_toa5_mg2() As DbSet(Of aws_toa5_mg2)
    Public Overridable Property bufr_crex_data() As DbSet(Of bufr_crex_data)
    Public Overridable Property bufr_crex_master() As DbSet(Of bufr_crex_master)
    Public Overridable Property bufr_indicators() As DbSet(Of bufr_indicators)
    Public Overridable Property ccitts() As DbSet(Of ccitt)
    Public Overridable Property climsoftusers() As DbSet(Of climsoftuser)
    Public Overridable Property code_flag() As DbSet(Of code_flag)
    Public Overridable Property data_forms() As DbSet(Of data_forms)
    Public Overridable Property faultresolutions() As DbSet(Of faultresolution)
    Public Overridable Property featuregeographicalpositions() As DbSet(Of featuregeographicalposition)
    Public Overridable Property flags() As DbSet(Of flag)
    Public Overridable Property flagtables() As DbSet(Of flagtable)
    Public Overridable Property form_agro1() As DbSet(Of form_agro1)
    Public Overridable Property form_daily2() As DbSet(Of form_daily2)
    Public Overridable Property form_hourly() As DbSet(Of form_hourly)
    Public Overridable Property form_hourly_time_selection() As DbSet(Of form_hourly_time_selection)
    Public Overridable Property form_hourlywind() As DbSet(Of form_hourlywind)
    Public Overridable Property form_monthly() As DbSet(Of form_monthly)
    Public Overridable Property form_synoptic_2_ra1() As DbSet(Of form_synoptic_2_ra1)
    Public Overridable Property form_synoptic2_tdcf() As DbSet(Of form_synoptic2_tdcf)
    Public Overridable Property instruments() As DbSet(Of instrument)
    Public Overridable Property instrumentfaultreports() As DbSet(Of instrumentfaultreport)
    Public Overridable Property instrumentinspections() As DbSet(Of instrumentinspection)
    Public Overridable Property language_translation() As DbSet(Of language_translation)
    Public Overridable Property obselements() As DbSet(Of obselement)
    Public Overridable Property observationfinals() As DbSet(Of observationfinal)
    Public Overridable Property observationinitials() As DbSet(Of observationinitial)
    Public Overridable Property observationschedules() As DbSet(Of observationschedule)
    Public Overridable Property obsscheduleclasses() As DbSet(Of obsscheduleclass)
    Public Overridable Property paperarchives() As DbSet(Of paperarchive)
    Public Overridable Property paperarchivedefinitions() As DbSet(Of paperarchivedefinition)
    Public Overridable Property physicalfeatures() As DbSet(Of physicalfeature)
    Public Overridable Property physicalfeatureclasses() As DbSet(Of physicalfeatureclass)
    Public Overridable Property qc_interelement_1() As DbSet(Of qc_interelement_1)
    Public Overridable Property qc_interelement_2() As DbSet(Of qc_interelement_2)
    Public Overridable Property qc_interelement_relationship_definition() As DbSet(Of qc_interelement_relationship_definition)
    Public Overridable Property qcstatusdefinitions() As DbSet(Of qcstatusdefinition)
    Public Overridable Property qctypes() As DbSet(Of qctype)
    Public Overridable Property regkeys() As DbSet(Of regkey)
    Public Overridable Property seq_daily_element() As DbSet(Of seq_daily_element)
    Public Overridable Property seq_element() As DbSet(Of seq_element)
    Public Overridable Property seq_month_day() As DbSet(Of seq_month_day)
    Public Overridable Property seq_month_day_leap_yr() As DbSet(Of seq_month_day_leap_yr)
    Public Overridable Property seq_month_day_synoptime() As DbSet(Of seq_month_day_synoptime)
    Public Overridable Property seq_month_day_synoptime_leap_yr() As DbSet(Of seq_month_day_synoptime_leap_yr)
    Public Overridable Property stations() As DbSet(Of station)
    Public Overridable Property stationelements() As DbSet(Of stationelement)
    Public Overridable Property stationidalias() As DbSet(Of stationidalia)
    Public Overridable Property stationlocationhistories() As DbSet(Of stationlocationhistory)
    Public Overridable Property stationnetworkdefinitions() As DbSet(Of stationnetworkdefinition)
    Public Overridable Property stationqualifiers() As DbSet(Of stationqualifier)
    Public Overridable Property synopfeatures() As DbSet(Of synopfeature)
    Public Overridable Property tblproducts() As DbSet(Of tblproduct)
    Public Overridable Property tdcf_indicators() As DbSet(Of tdcf_indicators)
    Public Overridable Property tm_307091() As DbSet(Of tm_307091)
    Public Overridable Property aws_malawi12() As DbSet(Of aws_malawi12)
    Public Overridable Property aws1() As DbSet(Of aws1)
    Public Overridable Property seq_month_day_element() As DbSet(Of seq_month_day_element)
    Public Overridable Property seq_month_day_element_leap_yr() As DbSet(Of seq_month_day_element_leap_yr)

End Class
