'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class obselement
    Public Property elementId As Long
    Public Property abbreviation As String
    Public Property elementName As String
    Public Property description As String
    Public Property elementScale As Nullable(Of Decimal)
    Public Property upperLimit As String
    Public Property lowerLimit As String
    Public Property units As String
    Public Property elementtype As String
    Public Property qcTotalRequired As Nullable(Of Integer)
    Public Property selected As SByte

    Public Overridable Property observationinitials As ICollection(Of observationinitial) = New HashSet(Of observationinitial)
    Public Overridable Property observationfinals As ICollection(Of observationfinal) = New HashSet(Of observationfinal)

End Class
