'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class observationschedule
    Public Property id As Long
    Public Property classifiedInto As String
    Public Property startTime As String
    Public Property endTime As String
    Public Property interval As String
    Public Property additionalObsTime As String

    Public Overridable Property obsscheduleclass As obsscheduleclass

End Class
