'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class paperarchivedefinition
    Public Property formId As String
    Public Property description As String

    Public Overridable Property paperarchives As ICollection(Of paperarchive) = New HashSet(Of paperarchive)

End Class
