'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class qc_interelement_relationship_definition
    Public Property elementId_1 As Integer
    Public Property relationship As String
    Public Property elementId_2 As Integer

End Class
