'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class qc_interelement_1
    Public Property id As Long
    Public Property stationId_1 As String
    Public Property elementId_1 As Integer
    Public Property obsDatetime_1 As Date
    Public Property obsValue_1 As Nullable(Of Integer)
    Public Property qcStatus_1 As Nullable(Of Integer)
    Public Property acquisitionType_1 As Nullable(Of Integer)
    Public Property obsLevel_1 As String
    Public Property capturedBy_1 As String
    Public Property dataForm_1 As String

End Class
