'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class qc_interelement_2
    Public Property id As Long
    Public Property stationId_2 As String
    Public Property elementId_2 As Integer
    Public Property obsDatetime_2 As Date
    Public Property obsValue_2 As Nullable(Of Integer)
    Public Property qcStatus_2 As Nullable(Of Integer)
    Public Property acquisitionType_2 As Nullable(Of Integer)
    Public Property obsLevel_2 As String
    Public Property capturedBy_2 As String
    Public Property dataForm_2 As String

End Class
