'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class stationidalia
    Public Property idAlias As String
    Public Property refersTo As String
    Public Property belongsTo As String
    Public Property idAliasBeginDate As String
    Public Property idAliasEndDate As String

    Public Overridable Property station As station

End Class
