'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tdcf_indicators
    Public Property id As Long
    Public Property CREX_Edition As Nullable(Of Integer)
    Public Property CREX_Table As Nullable(Of Integer)
    Public Property BUFR_Table As Nullable(Of Integer)
    Public Property Local_Table As Nullable(Of Integer)
    Public Property Data_Category As Nullable(Of Integer)
    Public Property Data_SubCategory As Nullable(Of Integer)
    Public Property Originating_Centre As Nullable(Of Integer)

End Class
