'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class aws_sasscal1
    Public Property Cols As Integer
    Public Property Element_Abbreviation As String
    Public Property Element_Name As String
    Public Property Element_Details As String
    Public Property Climsoft_Element As String
    Public Property Bufr_Element As String
    Public Property unit As String
    Public Property lower_limit As String
    Public Property upper_limit As String
    Public Property obsv As String

End Class
