'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class aws_basestation
    Public Property ftpId As String
    Public Property inputFolder As String
    Public Property ftpMode As String
    Public Property userName As String
    Public Property password As String

End Class
