'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class data_forms
    Public Property id As Long
    Public Property order_num As Nullable(Of Long)
    Public Property table_name As String
    Public Property form_name As String
    Public Property description As String
    Public Property selected As Nullable(Of SByte)
    Public Property val_start_position As Nullable(Of Long)
    Public Property val_end_position As Nullable(Of Long)
    Public Property elem_code_location As String
    Public Property sequencer As String
    Public Property entry_mode As Byte

End Class
