'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class form_hourlywind
    Public Property stationId As String
    Public Property yyyy As Integer
    Public Property mm As Integer
    Public Property dd As Integer
    Public Property elem_112_00 As String
    Public Property elem_112_01 As String
    Public Property elem_112_02 As String
    Public Property elem_112_03 As String
    Public Property elem_112_04 As String
    Public Property elem_112_05 As String
    Public Property elem_112_06 As String
    Public Property elem_112_07 As String
    Public Property elem_112_08 As String
    Public Property elem_112_09 As String
    Public Property elem_112_10 As String
    Public Property elem_112_11 As String
    Public Property elem_112_12 As String
    Public Property elem_112_13 As String
    Public Property elem_112_14 As String
    Public Property elem_112_15 As String
    Public Property elem_112_16 As String
    Public Property elem_112_17 As String
    Public Property elem_112_18 As String
    Public Property elem_112_19 As String
    Public Property elem_112_20 As String
    Public Property elem_112_21 As String
    Public Property elem_112_22 As String
    Public Property elem_112_23 As String
    Public Property ddflag00 As String
    Public Property ddflag01 As String
    Public Property ddflag02 As String
    Public Property ddflag03 As String
    Public Property ddflag04 As String
    Public Property ddflag05 As String
    Public Property ddflag06 As String
    Public Property ddflag07 As String
    Public Property ddflag08 As String
    Public Property ddflag09 As String
    Public Property ddflag10 As String
    Public Property ddflag11 As String
    Public Property ddflag12 As String
    Public Property ddflag13 As String
    Public Property ddflag14 As String
    Public Property ddflag15 As String
    Public Property ddflag16 As String
    Public Property ddflag17 As String
    Public Property ddflag18 As String
    Public Property ddflag19 As String
    Public Property ddflag20 As String
    Public Property ddflag21 As String
    Public Property ddflag22 As String
    Public Property ddflag23 As String
    Public Property elem_111_00 As String
    Public Property elem_111_01 As String
    Public Property elem_111_02 As String
    Public Property elem_111_03 As String
    Public Property elem_111_04 As String
    Public Property elem_111_05 As String
    Public Property elem_111_06 As String
    Public Property elem_111_07 As String
    Public Property elem_111_08 As String
    Public Property elem_111_09 As String
    Public Property elem_111_10 As String
    Public Property elem_111_11 As String
    Public Property elem_111_12 As String
    Public Property elem_111_13 As String
    Public Property elem_111_14 As String
    Public Property elem_111_15 As String
    Public Property elem_111_16 As String
    Public Property elem_111_17 As String
    Public Property elem_111_18 As String
    Public Property elem_111_19 As String
    Public Property elem_111_20 As String
    Public Property elem_111_21 As String
    Public Property elem_111_22 As String
    Public Property elem_111_23 As String
    Public Property total As String
    Public Property signature As String

End Class
